version: '3.7'
services:
  publisher:
    image: efrecon/mqtt-client
    command: pub -h host.docker.internal -t alfaisal_uni -m "<Amaan Zubairi here 200226>"
    networks:
      - se443_test_net
    restart: always
    deploy:
      replicas: 3
      restart_policy:
        condition: always
    depends_on:
      - subscriber
  subscriber:
    image: efrecon/mqtt-client
    command: sub -h host.docker.internal -t alfaisal_uni -v
    networks:
      - se443_test_net
    restart: always
    deploy:
      replicas: 3
    depends_on:
      - broker
  broker:
    image: eclipse-mosquitto
    networks:
      - se443_test_net
    restart: always
    deploy:
      replicas: 3
networks:
  se443_test_net:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
